QT += core network
QT -= gui
CONFIG += console c++11
CONFIG -= app_bundle
TEMPLATE = app
TARGET = passwordhash_tests
INCLUDEPATH += ../Server
SOURCES += passwordhash_test.cpp ../Server/passwordhash.cpp
HEADERS += ../Server/passwordhash.h
